### PR TITLE
add length param to decode function

### PR DESCRIPTION
**Pull request by roaminro**
Thanks for you awesome work @piotr-oles! I just needed to be able to give a decoder the length of the buffer, so I added an optional parameter to the decode function.

### CODE REVIEW

**Comment by piotr-oles** [comment]
Thanks for the PR! It looks good, but I'm curious what is your use case? :)

**Comment by roaminro** [comment]
So, I'm basically creating a "Contract Development Toolkit" (CDT) for a blockchain called Koinos (https://koinos.io). This CDT is just an interface between AseemblyScript and the WASM virtual machine (VM), they use "Fizzy" as their WASM VM. Their VM exposes an environment function that you can call to trigger different "system calls" (syscalls) and these system calls use Protobuf, so you need to use Protobuf to interact with them. When you call the "invoke_system_call" function, you give them a pointer to a buffer that they will use to return data (as Protobuf). I had some cases where these system calls were getting "trapped" because the "as-proto" deserializer was trying to read the entire "read buffer" when it should actually only read the number of bytes that were written by the WASM VM. The read buffer is always 1024 bytes, but the result of a syscall can be way less than that. The syscalls return the number of bytes that were written to the read buffer, so by giving this number to "as-proto" I can ensure that your library will only try to deserialize what's needed. Here's an example of how I use it (with a modified version of "as-proto": 

```js
export function getEntryPoint(): u32 {
    const args = new chain.get_entry_point_arguments();
    const encodedArgs = Protobuf.encode(args, chain.get_entry_point_arguments.encode);
    const readBuffer = new Uint8Array(MAX_BUFFER_SIZE);
    const len = env.invoke_system_call(system_call_id.get_entry_point, readBuffer.dataStart as u32, MAX_BUFFER_SIZE, encodedArgs.dataStart as u32, encodedArgs.byteLength);
    const result = Protobuf.decode<chain.get_entry_point_result>(readBuffer, chain.get_entry_point_result.decode, len);

    return result.value;
  }
```

**Comment by piotr-oles** [comment]
Make sense :) Could you rebase the branch to the latest main? I added missing CI actions for pull request event

**Comment by roaminro** [comment]
done, thanks!

**Review by piotr-oles — APPROVED** [review]

**Pull request merged**
